// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldcuqvozbqityjeflgmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkY3Vxdm96YnFpdHlqZWZsZ21qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMTUzMTgsImV4cCI6MjA3MDY5MTMxOH0.htMGTa9ysAU-PkRaD-BDBVJMKNjjr0unps1Dvjdwid0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});